/**
 * Created by zhangyou on 19/7/17.
 */

module.exports = {
    '#d84315': {
        darkPrimaryColor: '#D32F2F',
        primaryColor: '#d84315',
        lightPrimaryColor: '#FFCDD2',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#FF5252',
        primaryTextColor: '#212121',
        textPrimaryColor: '#FFFFFF',
        secondaryTextColor: '#757575',
        dividerColor: '#BDBDBD',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#ef6c00': {
        darkPrimaryColor: '#E64A19',
        primaryColor: '#ef6c00',
        lightPrimaryColor: '#FFCCBC',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#FF5722',
        primaryTextColor: '#212121',
        textPrimaryColor: '#ffffff',
        secondaryTextColor: '#aaa',
        dividerColor: '#e2e2e2',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#fdd835': {
        darkPrimaryColor: '#e59e00',
        primaryColor: '#ffda00',
        lightPrimaryColor: '#fff1b8',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#ffda00',
        primaryTextColor: '#212121',
        textPrimaryColor: '#ffffff',
        secondaryTextColor: '#aaa',
        dividerColor: '#e2e2e2',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#c0ca33': {
        darkPrimaryColor: '#689F38',
        primaryColor: '#c0ca33',
        lightPrimaryColor: '#DCEDC8',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#8BC34A',
        primaryTextColor: '#212121',
        textPrimaryColor: '#212121',
        secondaryTextColor: '#757575',
        dividerColor: '#e2e2e2',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#558b2f': {
        darkPrimaryColor: '#388E3C',
        primaryColor: '#558b2f',
        lightPrimaryColor: '#C8E6C9',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#4CAF50',
        primaryTextColor: '#212121',
        textPrimaryColor: '#ffffff',
        secondaryTextColor: '#757575',
        dividerColor: '#e2e2e2',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#2e7d32': {
        darkPrimaryColor: '#388E3C',
        primaryColor: '#2e7d32',
        lightPrimaryColor: '#C8E6C9',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#4CAF50',
        primaryTextColor: '#212121',
        textPrimaryColor: '#ffffff',
        secondaryTextColor: '#757575',
        dividerColor: '#e2e2e2',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#00897b': {
        darkPrimaryColor: '#00796B',
        primaryColor: '#00897b',
        lightPrimaryColor:  '#B2DFDB',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#009688',
        primaryTextColor: '#212121',
        textPrimaryColor: '#ffffff',
        secondaryTextColor: '#757575',
        dividerColor: '#BDBDBD',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#0091ea': {
        darkPrimaryColor: '#0288D1',
        primaryColor: '#0091ea',
        lightPrimaryColor: '#B3E5FC',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#4CAF50',
        primaryTextColor: '#212121',
        textPrimaryColor: '#FFFFFF',
        secondaryTextColor: '#757575',
        dividerColor: '#BDBDBD',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#0277bd': {
        darkPrimaryColor: '#1976D2',
        primaryColor: '#0277bd',
        lightPrimaryColor: '#BBDEFB',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#448AFF',
        primaryTextColor: '#212121',
        textPrimaryColor: '#FFFFFF',
        secondaryTextColor: '#757575',
        dividerColor: '#BDBDBD',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#0561a0': {
        darkPrimaryColor: '#1976D2',
        primaryColor: '#0561a0',
        lightPrimaryColor: '#BBDEFB',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#448AFF',
        primaryTextColor: '#212121',
        textPrimaryColor: '#FFFFFF',
        secondaryTextColor: '#757575',
        dividerColor: '#BDBDBD',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#2f3e89': {
        darkPrimaryColor: '#303F9F',
        primaryColor: '#2f3e89',
        lightPrimaryColor: '#C5CAE9',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#536DFE',
        primaryTextColor: '#212121',
        textPrimaryColor: '#FFFFFF',
        secondaryTextColor: '#757575',
        dividerColor: '#BDBDBD',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    },
    '#3a3a3a': {
        darkPrimaryColor: '#1976D2',
        primaryColor: '#3a3a3a',
        lightPrimaryColor: '#BBDEFB',
        negativeColor: '#e24949',
        disabledColor: '#e2e2e2',
        accentColor: '#448AFF',
        primaryTextColor: '#212121',
        textPrimaryColor: '#FFFFFF',
        secondaryTextColor: '#757575',
        dividerColor: '#BDBDBD',
        primaryBackgroundColor: '#FFFFFF',
        secondaryBackgroundColor: '#F8F8F8'
    }
};
